"""Dlux models.

Every model class is imported here: Django resolves models through
`<app>.models`, so a class that is not re-exported is invisible to the app
registry and to migrations.
"""

from ._shared import (  # noqa: F401
    logger,
)
from .base import (  # noqa: F401
    ScopeForeignKey,
    ScopedModel,
    SingletonModel,
    TranslationMixin,
)
from .settings import (  # noqa: F401
    SystemSettings,
    _SYSTEM_SETTINGS_CONFIG_DEFAULTS,
    _SYSTEM_SETTINGS_FLAT_CONFIG_FIELDS,
    _system_settings_config_get,
    _system_settings_config_property,
    _system_settings_config_set,
    default_allowed_fonts,
    default_allowed_themes,
    default_auth_config,
    default_backup_config,
    default_client_ip_config,
    default_email_config,
    default_extra_config,
    default_homepage_config,
    default_language_config,
    default_layout_config,
    default_log_config,
    default_login_config,
    default_navbar_config,
    default_notification_config,
    default_profile_config,
    default_public_root_config,
    default_registration_config,
    default_search_config,
    default_theme_config,
    default_titlebar_config,
    default_typography_config,
    SystemSettingsSnapshot,
)
from .scopes import (  # noqa: F401
    GroupMembership,
    GroupProfile,
    Scope,
    ScopeSettings,
)
from .asset_field import (  # noqa: F401
    ManagedAssetField,
    default_namespace_for_model,
    get_asset_field,
    registered_asset_fields,
)
from .assets import (  # noqa: F401
    DEFAULT_ASSET_NAMESPACE,
    FONT_ASSET_NAMESPACE,
    INSTALLER_ASSET_NAMESPACE,
    SHARED_ASSET_NAMESPACE,
    ManagedAsset,
    ManagedFontFamily,
    ManagedFontVariant,
    default_namespace_for_kind,
    managed_asset_upload_to,
    ScanLinkRelease,
)
from .notifications import (  # noqa: F401
    DluxNotification,
    DluxNotificationRule,
    DluxNotificationState,
    DluxNotificationWatch,
)
from .users import (  # noqa: F401
    Profile,
    PublicRegistration,
    TrustedDevice,
    UserKnownDevice,
    UserPresenceSession,
    apply_public_registration_defaults,
)
from .backup import (  # noqa: F401
    ReportBackup,
    SystemBackup,
    SystemRestore,
    generate_report_backup_token,
)
from .updater import (  # noqa: F401
    DluxControlLinkRequest,
    DluxImageUpdate,
    DluxUpdateRun,
    DluxUpdateState,
)
from .activity import (  # noqa: F401
    ActivityLog,
    Section,
    UserActivityLog,
)

__all__ = [
    'ActivityLog',
    'DluxControlLinkRequest',
    'DluxImageUpdate',
    'DluxNotification',
    'DluxNotificationRule',
    'DluxNotificationState',
    'DluxNotificationWatch',
    'DluxUpdateRun',
    'DluxUpdateState',
    'GroupMembership',
    'GroupProfile',
    'DEFAULT_ASSET_NAMESPACE',
    'FONT_ASSET_NAMESPACE',
    'INSTALLER_ASSET_NAMESPACE',
    'SHARED_ASSET_NAMESPACE',
    'ManagedAsset',
    'ManagedAssetField',
    'ManagedFontFamily',
    'ManagedFontVariant',
    'default_namespace_for_kind',
    'default_namespace_for_model',
    'get_asset_field',
    'registered_asset_fields',
    'Profile',
    'PublicRegistration',
    'ReportBackup',
    'Scope',
    'ScopeForeignKey',
    'ScopeSettings',
    'ScopedModel',
    'Section',
    'SingletonModel',
    'SystemBackup',
    'SystemRestore',
    'SystemSettings',
    'TranslationMixin',
    'TrustedDevice',
    'UserActivityLog',
    'UserKnownDevice',
    'UserPresenceSession',
    'apply_public_registration_defaults',
    'default_allowed_fonts',
    'default_allowed_themes',
    'default_auth_config',
    'default_backup_config',
    'default_client_ip_config',
    'default_email_config',
    'default_extra_config',
    'default_homepage_config',
    'default_language_config',
    'default_layout_config',
    'default_log_config',
    'default_login_config',
    'default_navbar_config',
    'default_notification_config',
    'default_profile_config',
    'default_public_root_config',
    'default_registration_config',
    'default_search_config',
    'default_theme_config',
    'default_titlebar_config',
    'default_typography_config',
    'generate_report_backup_token',
    'logger',
    'managed_asset_upload_to',
]
