# Generated by Django 5.2.8 on 2026-04-27 20:41

import django.db.models.deletion
import microsys.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_sections', 'View sections'), ('manage_sections', 'Manage sections')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Scope')),
            ],
            options={
                'verbose_name': 'Scope',
                'verbose_name_plural': 'Scopes',
            },
        ),
        migrations.CreateModel(
            name='ScopeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Enable Scopes')),
                ('auto_create_user_scope', models.BooleanField(default=False, verbose_name='Auto-create scope for each user')),
            ],
            options={
                'verbose_name': 'Scope Settings',
                'verbose_name_plural': 'Scope Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_names', models.JSONField(blank=True, default=dict, verbose_name='System Names by Language')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='microsys/branding/', verbose_name='System Logo (Logo)')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='microsys/branding/', verbose_name='Site Icon (Favicon)')),
                ('default_language', models.CharField(default='en', max_length=10, verbose_name='Default Language')),
                ('default_theme', models.CharField(default='light', max_length=20, verbose_name='Default Theme')),
                ('default_table_density', models.CharField(choices=[('balanced', 'Balanced'), ('dense', 'Dense'), ('roomy', 'Roomy')], default='balanced', max_length=20, verbose_name='Default Table Density')),
                ('allowed_themes', models.JSONField(blank=True, default=microsys.models.default_allowed_themes, verbose_name='Allowed Themes')),
                ('allow_user_theme_override', models.BooleanField(default=True, verbose_name='Allow User Theme Override')),
                ('allow_user_language_override', models.BooleanField(default=True, verbose_name='Allow User Language Override')),
                ('home_url', models.CharField(default='/accounts/profile/', max_length=255, verbose_name='Home URL')),
                ('is_configured', models.BooleanField(default=False, verbose_name='Is Configured')),
                ('email_2fa', models.BooleanField(default=False, verbose_name='Enable Email 2FA')),
                ('public_root', models.BooleanField(default=False, verbose_name='Public Root Access')),
                ('languages', models.JSONField(blank=True, default=dict, verbose_name='Available Languages')),
                ('translations_override', models.JSONField(blank=True, default=dict, verbose_name='Translations Override')),
                ('sidebar_config', models.JSONField(blank=True, default=dict, verbose_name='Sidebar Configuration')),
                ('titlebar_config', models.JSONField(blank=True, default=microsys.models.default_titlebar_config, verbose_name='Titlebar Configuration')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='User Preferences')),
                ('is_email_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA via Email')),
                ('is_phone_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA via Phone')),
                ('is_totp_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA via App')),
                ('totp_secret', models.CharField(blank=True, max_length=32, null=True, verbose_name='TOTP Secret')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Backup Codes')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='Scope')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'permissions': [('manage_staff', 'Can manage staff'), ('view_activitylog', 'View activity log'), ('manage_scopes', 'Can manage scopes and all users')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Name')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Document Number')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='Details')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='Scope')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'default_permissions': (),
            },
        ),
    ]
