# Generated by Django 5.2.8 on 2026-04-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='is_configured',
        ),
    ]
