# Generated by Django 5.2.8 on 2026-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_theme',
            field=models.CharField(default='light', max_length=20, verbose_name='المظهر الافتراضي'),
        ),
    ]
