# Generated by Django migration for public_root feature

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('microsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='public_root',
            field=models.BooleanField(default=False, verbose_name='Public Root Access'),
        ),
    ]
