# Generated by Django migration for Microsys table density defaults

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('microsys', '0002_systemsettings_public_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_2fa',
            field=models.BooleanField(default=False, verbose_name='Enable Email 2FA'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_table_density',
            field=models.CharField(
                choices=[('balanced', 'Balanced'), ('dense', 'Dense'), ('roomy', 'Roomy')],
                default='balanced',
                max_length=20,
                verbose_name='الكثافة الافتراضية للجداول',
            ),
        ),
    ]
