# Generated by Django 5.2.8 on 2026-04-02 23:30

from django.db import migrations, models


LEGACY_NAMES = {'ادارة النظام', 'إدارة النظام'}


def clear_legacy_unconfigured_name(apps, schema_editor):
    SystemSettings = apps.get_model('microsys', 'SystemSettings')
    try:
        settings_obj = SystemSettings.objects.get(pk=1)
    except SystemSettings.DoesNotExist:
        return

    if not getattr(settings_obj, 'is_configured', False) and settings_obj.name in LEGACY_NAMES:
        settings_obj.name = ''
        settings_obj.save(update_fields=['name'])


def restore_legacy_unconfigured_name(apps, schema_editor):
    SystemSettings = apps.get_model('microsys', 'SystemSettings')
    try:
        settings_obj = SystemSettings.objects.get(pk=1)
    except SystemSettings.DoesNotExist:
        return

    if not getattr(settings_obj, 'is_configured', False) and settings_obj.name == '':
        settings_obj.name = 'ادارة النظام'
        settings_obj.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0002_systemsettings_default_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم النظام (عربي)'),
        ),
        migrations.RunPython(
            clear_legacy_unconfigured_name,
            restore_legacy_unconfigured_name,
        ),
    ]
