# Generated by Django migration for Microsys theme/sidebar/titlebar customization

from django.db import migrations, models


def default_allowed_themes():
    return ['light', 'blue', 'gold', 'green', 'red', 'mono', 'dark', 'gothic', 'retro', 'neon']


def default_titlebar_config():
    return {
        'show_title': True,
        'show_logo': True,
        'show_home_button': True,
        'home_shape': 'circle',
        'title_align': 'start',
        'title_size': 'md',
        'height': 'balanced',
        'surface': 'default',
    }


class Migration(migrations.Migration):
    dependencies = [
        ('microsys', '0003_systemsettings_email_2fa_default_table_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_themes',
            field=models.JSONField(blank=True, default=default_allowed_themes, verbose_name='المظاهر المسموح بها'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_user_theme_override',
            field=models.BooleanField(default=True, verbose_name='السماح للمستخدم بتغيير المظهر'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allow_user_language_override',
            field=models.BooleanField(default=True, verbose_name='السماح للمستخدم بتغيير اللغة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='titlebar_config',
            field=models.JSONField(blank=True, default=default_titlebar_config, verbose_name='إعدادات شريط العنوان'),
        ),
    ]
