# Generated by Django 6.0.5 on 2026-05-16 09:39

import microsys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0004_client_ip_and_trusted_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='allow_user_font_override',
            field=models.BooleanField(default=True, verbose_name='Allow User Font Override'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='allowed_fonts',
            field=models.JSONField(blank=True, default=microsys.models.default_allowed_fonts, verbose_name='Allowed Fonts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_fonts',
            field=models.JSONField(blank=True, default=dict, verbose_name='Default Fonts by Language'),
        ),
    ]
