# Generated by Django on 2026-05-22

import microsys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0005_systemsettings_allow_user_font_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='navbar_config',
            field=models.JSONField(blank=True, default=microsys.models.default_navbar_config, verbose_name='Nav Bar Configuration'),
        ),
    ]
