# Generated by Django on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsys', '0006_systemsettings_navbar_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='prevent_multiple_active_sessions',
            field=models.BooleanField(default=False, verbose_name='Prevent Multiple Active Sessions'),
        ),
    ]
