# Generated by Django 6.0.6 on 2026-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0005_backup_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembackup',
            name='media_included',
            field=models.BooleanField(db_default=True, default=True, verbose_name='Media Included'),
        ),
        migrations.AddField(
            model_name='dluxupdaterun',
            name='backup_mode',
            field=models.CharField(choices=[('full', 'Full (database + media)'), ('data', 'Quick (data only)'), ('skip', 'Skip backup')], db_default='data', default='data', max_length=8, verbose_name='Backup Mode'),
        ),
    ]
