# Generated by Django 6.0.6 on 2026-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0009_public_registration_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='dluxupdatestate',
            name='skipped_versions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Skipped Versions'),
        ),
    ]
