# Generated by Django 6.0.6 on 2026-07-24 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0011_dluximageupdate_agent_correlation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DluxControlLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('enroll', 'Enroll'), ('cancel', 'Cancel')], default='enroll', max_length=16, verbose_name='Action')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Operation ID')),
                ('control_url', models.CharField(blank=True, max_length=500, verbose_name='Control URL')),
                ('pairing_token', models.CharField(blank=True, max_length=255, verbose_name='Pairing Token')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Dlux Control Link Request',
                'verbose_name_plural': 'Dlux Control Link Requests',
                'ordering': ['created_at'],
            },
        ),
    ]
