# Generated by Django 6.0.6 on 2026-07-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0012_dluxcontrollinkrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_permissions': (), 'permissions': [('manage_staff', 'Can manage staff'), ('manage_scopes', 'Can manage scopes and all users'), ('view_reports', 'Can view reports'), ('view_audit_fields', 'Can view audit fields (created/updated by/at) in tables and detail views'), ('download_backup', 'Can download backup')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
