# Generated by Django 6.0.8 on 2026-09-02 17:46

from django.conf import settings
from django.db import migrations, models


# No data migration, and no single default value either.
#
# Every asset predating this column is branding, a font, or a ScanLink
# installer — three different pools — so stamping them all with one namespace
# would be wrong for two of the three. They are left empty instead, and an empty
# namespace reads as "whatever this kind defaults to" (`effective_namespace`),
# which is right for all three at once.
#
# That also keeps the release inline-installable: a `RunPython` is outside the
# inline-safe operation allowlist (CreateModel / AddField / AddIndex /
# AlterModelOptions). The column self-heals — `ManagedAsset.save()` fills in a
# concrete namespace the first time any row is written.


class Migration(migrations.Migration):

    dependencies = [
        ('dlux', '0017_ribbon_config_and_notification_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managedasset',
            name='namespace',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=100, verbose_name='Asset Namespace'),
        ),
        migrations.AddIndex(
            model_name='managedasset',
            index=models.Index(fields=['namespace', 'kind', 'is_active'], name='dlux_asset_ns_kind_idx'),
        ),
    ]
