# Generated by Django 6.1 on 2026-09-22 22:52

import dlux.models.backup
from django.db import migrations, models


class Migration(migrations.Migration):
    """The Operations card's run log: one row per operation handed to Composer.

    Additive and inline-safe — a new table only. A deployment running the
    previous release against this schema never reads it.
    """

    dependencies = [
        ('dlux', '0022_update_state_check_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='DluxOpsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=dlux.models.backup.generate_report_backup_token, editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('operation', models.CharField(db_index=True, max_length=32, verbose_name='Operation')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16, verbose_name='Status')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('requested_by_username', models.CharField(blank=True, max_length=150, verbose_name='Requested By')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Result')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Requested At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Dlux Operations Run',
                'verbose_name_plural': 'Dlux Operations Runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='dlux_ops_active_idx')],
            },
        ),
    ]
