# Generated by Django 6.1 on 2026-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    """System backup options: encryption mode, portable scope, cancel, console log.

    Additive and inline-safe — every new column carries a ``db_default``, so the
    previous release can still insert SystemBackup rows against this schema. The
    status change only adds the ``cancelled`` choice, so it is state-only (see
    docs/RELEASING.md).
    """

    dependencies = [
        ('dlux', '0023_ops_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembackup',
            name='encryption',
            field=models.CharField(choices=[('passphrase', 'Passphrase'), ('server_key', 'Server key'), ('none', 'Not encrypted')], db_default='server_key', default='server_key', max_length=12, verbose_name='Encryption'),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='progress_log',
            field=models.JSONField(blank=True, db_default=[], default=list, verbose_name='Progress Log'),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='system_data_included',
            field=models.BooleanField(db_default=True, default=True, verbose_name='System Data Included'),
        ),
        # State-only: `choices` is validated in Python, never in the schema.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='systembackup',
                    name='status',
                    field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12, verbose_name='Status'),
                ),
            ],
        ),
    ]
