# Generated by Django 6.1 on 2026-10-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Incremental backup chains: kind, parent, chain id, sequence, index digests.

    Additive and inline-safe: the parent link is nullable and every other
    column carries a ``db_default``, so the previous release can still insert
    SystemBackup rows (they read as full backups outside any chain).
    """

    dependencies = [
        ('dlux', '0024_system_backup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='systembackup',
            name='chain_id',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=64, verbose_name='Chain'),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='index_root',
            field=models.CharField(blank=True, db_default='', default='', max_length=64, verbose_name='Index Root'),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='kind',
            field=models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], db_default='full', default='full', max_length=12, verbose_name='Kind'),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='migration_digest',
            field=models.CharField(blank=True, db_default='', default='', max_length=64, verbose_name='Migration Digest'),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dlux.systembackup', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='systembackup',
            name='sequence',
            field=models.PositiveIntegerField(db_default=0, default=0, verbose_name='Sequence'),
        ),
    ]
