#!/usr/bin/env python3
"""Apply the Tier-1 translation-key unification (identical EN + AR duplicates).

For every group of keys that share the *same* English and Arabic value, one
canonical key is kept and the rest are **retired**: their literal entries are
removed from ``dlux/translations.py`` and recorded in a generated alias map
(``dlux/translations/aliases.py``). At runtime ``get_strings()`` resolves each
retired key to its canonical key's value, so:

* nothing breaks (retired keys still resolve — backward compatible for Dlux and
  downstream templates, and for keys looked up by computed name);
* the maintained string table shrinks (retired keys no longer carry their own
  value);
* editing the canonical once changes every alias ("change globally").

Dry-run by default — prints the alias map + a unified diff. Pass ``--apply`` to
write both files.

Usage:
    python scripts/apply_tier1_unification.py            # preview
    python scripts/apply_tier1_unification.py --apply     # write
"""

from __future__ import annotations

import argparse
import ast
import difflib
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRANSLATIONS = ROOT / "dlux" / "translations.py"
ALIASES_FILE = ROOT / "dlux" / "translations/aliases.py"


def _dlux_strings_dict(tree):
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Dict) \
                and any(isinstance(t, ast.Name) and t.id == "DLUX_STRINGS" for t in node.targets):
            return node.value
    raise SystemExit("DLUX_STRINGS not found.")


def load():
    """Return (source, {lang: {key: value}}, {lang: {key: (start, end)}})."""
    source = TRANSLATIONS.read_text(encoding="utf-8")
    top = _dlux_strings_dict(ast.parse(source))
    values: dict[str, dict[str, str]] = {}
    positions: dict[str, dict[str, tuple[int, int]]] = {}
    for lk, lv in zip(top.keys, top.values):
        if not (isinstance(lk, ast.Constant) and isinstance(lk.value, str) and isinstance(lv, ast.Dict)):
            continue
        vals, pos = {}, {}
        for k, v in zip(lv.keys, lv.values):
            if not (isinstance(k, ast.Constant) and isinstance(k.value, str)):
                continue
            pos[k.value] = (k.lineno, getattr(v, "end_lineno", None) or v.lineno)
            if isinstance(v, ast.Constant) and isinstance(v.value, str):
                vals[k.value] = v.value
        values[lk.value] = vals
        positions[lk.value] = pos
    return source, values, positions


def canonical(keys):
    return sorted(keys, key=lambda k: (len(k), k))[0]


def build_aliases(values):
    en, ar = values.get("en", {}), values.get("ar", {})
    groups = defaultdict(list)
    for key, val in en.items():
        groups[val.strip()].append(key)

    aliases: dict[str, str] = {}
    for _val, keys in groups.items():
        if len(keys) < 2:
            continue
        ar_vals = {ar.get(k, "").strip() for k in keys if k in ar}
        if len(ar_vals) > 1:
            continue  # Tier 2 (AR differs) — not safe to auto-unify
        keep = canonical(keys)
        for k in keys:
            if k != keep:
                aliases[k] = keep
    return dict(sorted(aliases.items()))


def render_aliases_module(aliases):
    lines = [
        '"""Auto-generated by scripts/apply_tier1_unification.py — do not edit by hand.',
        "",
        "Maps each retired duplicate translation key to the canonical key it was",
        "unified into. dlux/translations.py get_strings() resolves these at runtime.",
        '"""',
        "",
        "STRING_ALIASES = {",
    ]
    for retired, keep in aliases.items():
        lines.append(f"    {retired!r}: {keep!r},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Apply Tier-1 translation unification.")
    ap.add_argument("--apply", action="store_true", help="Write the files (default: dry-run).")
    args = ap.parse_args(argv)

    source, values, positions = load()
    aliases = build_aliases(values)
    if not aliases:
        print("No Tier-1 duplicates to unify.")
        return 0

    retired = set(aliases)
    drop_lines: set[int] = set()
    for lang_pos in positions.values():
        for key in retired:
            if key in lang_pos:
                start, end = lang_pos[key]
                drop_lines.update(range(start, end + 1))

    original = source.splitlines(keepends=True)
    new = [ln for i, ln in enumerate(original, start=1) if i not in drop_lines]
    new_source = "".join(new)

    print(f"Tier-1 groups → {len(aliases)} retired key(s) aliased to "
          f"{len(set(aliases.values()))} canonical key(s); {len(drop_lines)} line(s) removed.")
    print("\nAlias map (retired -> canonical):")
    for retired_key, keep in list(aliases.items())[:15]:
        print(f"  {retired_key} -> {keep}")
    if len(aliases) > 15:
        print(f"  … +{len(aliases) - 15} more")

    diff = difflib.unified_diff(
        original, new,
        fromfile=f"a/{TRANSLATIONS.relative_to(ROOT)}",
        tofile=f"b/{TRANSLATIONS.relative_to(ROOT)}",
    )
    print("\n--- translations.py diff " + "-" * 30)
    # Print a bounded preview so the terminal isn't flooded.
    for i, line in enumerate(diff):
        if i > 60:
            print("  … (diff truncated)")
            break
        print(line, end="")

    if args.apply:
        ALIASES_FILE.write_text(render_aliases_module(aliases), encoding="utf-8")
        TRANSLATIONS.write_text(new_source, encoding="utf-8")
        print(f"\nAPPLIED: wrote {ALIASES_FILE.relative_to(ROOT)} and rewrote "
              f"{TRANSLATIONS.relative_to(ROOT)}. Run the test suite to confirm.")
    else:
        print(f"\nDRY-RUN: would alias {len(aliases)} key(s). Re-run with --apply.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
